### ISSUE TITLE
issue_id on jira_issue_worklog is not deterministic (depends on how item is queried)

### ISSUE THREAD

**Issue by mariusgrigaitis** [turbot/steampipe-plugin-jira#147]
**Describe the bug**
```sql
> select issue_id from jira_issue_worklog where id = '12986' and issue_id = 'IMT-120' limit 5;
+----------+
| issue_id |
+----------+
| IMT-120  |
+----------+
> select issue_id from jira_issue_worklog where id = '12986' and issue_id = '985530' limit 5;
+----------+
| issue_id |
+----------+
| 985530   |
+----------+
```

When querying for issue_worklog, it seems that `issue_id` column depends on the way worklog is queries. I don't believe this is expected. 

**Steampipe version (`steampipe -v`)**
Example: v1.0.2

**Plugin version (`steampipe plugin list`)**
Example: v1.0.0

**To reproduce**
```sql
> select issue_id from jira_issue_worklog where id = '12986' and issue_id = 'IMT-120' limit 5;
+----------+
| issue_id |
+----------+
| IMT-120  |
+----------+
```

**Expected behavior**
```sql
> select issue_id from jira_issue_worklog where id = '12986' and issue_id = 'IMT-120' limit 5;
+----------+
| issue_id |
+----------+
| 985530   |
+----------+
```

**Comment by misraved** [comment]
Fixed in https://github.com/turbot/steampipe-plugin-jira/commit/a0d71db8ae1c479665767a051c5af4ddbedadf08

**Comment by mariusgrigaitis** [comment]
@misraved I don't think it's fixed. I'm still able to reproduce it on master branch.

**Comment by ParthaI** [comment]
Hi @mariusgrigaitis, apologies for the delay in addressing this issue, I was able to reproduce the issue locally.

Findings:
- The Worklog API accepts either an **issue ID** or an **issue key** as input when making the call.
- In both cases, the API returns results correctly. However, the response **only includes the issue ID** (e.g., `985530`) and **does not include the issue key** (e.g., `IMT-120`).

From a database perspective, when a query is run with `issue_id = 'IMT-120'`, Steampipe applies the filter at the SQL level. Since the API returns only the numeric issue ID, this should result in a mismatch and leads to **empty results** — even though the API itself returns valid data. However, this is not happening with the current logic we have for the table. AS we are setting the `issue_id` value to whatever we passed in the query parameter.

The root of the issue is in [this PR](https://github.com/turbot/steampipe-plugin-jira/pull/151/files#diff-457cdcdfe39e71aed9762567fb7b565ae26be125200707c0ac5dbc3d77bda44aR174), where we mistakenly set the `issue_id` column from the **query parameter** instead of using the **value from the API response**.

---

Proposed Solutions:
1. Add a new `issue_key` column to support filtering worklogs by issue key explicitly and populate it from the query parameter.
2. We should only filter/display the result based on the API response, if there is any ismatch between the API response and the query parameter, we should not display that row(default behavior of a database).

I've implemented **solution 2** in [a new PR](https://github.com/turbot/steampipe-plugin-jira/pull/164), which ensures we filter and display results based on the API response.

Eg:
1. We will have the results in the case when we provided the issue_id in the where clause matched with the API response:
      ```
      > select issue_id from jira_issue_worklog where issue_id = '10041';
      +----------+
      | issue_id |
      +----------+
      | 10041    |
      +----------+
      ```
2. We will have empty rows if we provide the issue key in the query parameter(Due to the query level filtering)
      ```
      > select issue_id from jira_issue_worklog where issue_id = 'TEST6-3';
      +----------+
      | issue_id |
      +----------+
      +----------+
      ```

Thanks!
